
batch_size: 16
input_size: 256
train_samples: 100
epochs: 150
learning_rate: 0.001
seed: 1
num_workers: 6
weights:
  type: simclr
  path: outputs/2023-03-31/08-15-53/lightning_logs/z35miyut/checkpoints/epoch=995-step=157368-val_loss_ssl=3.99.ckpt
  freeze: false
architecture: null
model_save_path: final.ckpt
