
batch_size: 32
input_size: 128
train_samples: 100
epochs: 400
oversample: true
learning_rate: 0.01
seed: 1
num_workers: 6
weights:
  type: simclr
  path: outputs/2023-04-06/12-19-01/lightning_logs/uq7vzdxh/checkpoints/epoch=984-step=27580-val_loss_ssl=5.32.ckpt
  freeze: true
architecture: resnet34
model_save_path: final.ckpt
