
batch_size: 16
input_size: 256
train_samples: 100
epochs: 50
learning_rate: 0.0001
seed: 1
num_workers: 6
weights:
  type: simclr
  path: null
  freeze: False
architecture: null
model_save_path: final.ckpt

