
batch_size: 32
input_size: 256
train_samples: 100
epochs: 300
oversample: true
learning_rate: 0.01
seed: 1

weights:
  type: simclr
  path: null
  freeze: true
architecture: resnet34
model_save_path: final.ckpt

