
batch_size: 32
input_size: 256
train_samples: 100
epochs: 200
learning_rate: 0.001
seed: 1
num_workers: 6
weights:
  type: simclr
  path: null
  freeze: False
architecture: resnet34
model_save_path: final.ckpt

