
batch_size: 256
input_size: 256
train_samples: null
epochs: 100
learning_rate: 6e-2
seed: 1
num_workers: 6
weights:
  type: imagenet
  path: null
  freeze: False
architecture: resnet34
model_save_path: final.ckpt
