
batch_size: 32
input_size: 32
train_samples: 100
epochs: 20
learning_rate: 0.001
seed: 1
num_workers: 6
weights:
  type: imagenet
  path: null
  freeze: True
architecture: resnet18_swsl
model_save_path: final.ckpt

