
batch_size: 8
input_size: 64
train_samples: null
epochs: 2
learning_rate: 0.0001
seed: 1
num_workers: 6
weights:
  type: imagenet
  path: null
  freeze: False
architecture: null
model_save_path: final.ckpt

